USE library;
SELECT * FROM users;

ALTER TABLE Users MODIFY COLUMN UserPass VARCHAR(100);
UPDATE Users SET UserPass="$2a$10$TIEoJOWuSBELiPf4e8UixOLSz/QOUcrwERWtTTysnHNP0RCWU73Xa" WHERE UserID=1;
UPDATE Users set UserPass="$2a$10$ot2ZQ0ydm6LVlHZOlVfkcOrRoz0Yh4U1.1sthzihJCpiBLv7SZlUu" WHERE UserID=2;
UPDATE Users set UserPass="$2a$10$PixJsis2fFU1hJWWGaA8Oe9VC8g4YcoXGgOqqJgJTECNXqAMTPksC" WHERE UserID=3;